from config import DB_HOST, DB_PORT, DB_NAME, DB_USER, DB_PASS, SECRET_KEY

TESTING = True
SECRET_KEY = SECRET_KEY
SQLALCHEMY_DATABASE_URI = (
    f"postgresql://{DB_USER}:{DB_PASS}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)
