"""Add TripInvites

Revision ID: 00e6dcbccd38
Revises: 18ede4529cb0
Create Date: 2025-06-18 06:45:30.227954

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '00e6dcbccd38'
down_revision = '18ede4529cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_invite',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('session_uuid', sa.UUID(), nullable=False),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_uuid'], ['trip_session.uuid'], name=op.f('fk_trip_invite_session_uuid_trip_session')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_trip_invite'))
    )
    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.UUID(), nullable=True))
        batch_op.alter_column('join_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_trip_participant_uuid'), ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trip_participant_uuid'), type_='unique')
        batch_op.alter_column('join_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('uuid')

    op.drop_table('trip_invite')
    # ### end Alembic commands ###
