"""delete segment_id from POI

Revision ID: 03926882b88b
Revises: df6e49e58d18
Create Date: 2025-06-10 15:31:49.432477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03926882b88b'
down_revision = 'df6e49e58d18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poi_segment_id_fkey'), type_='foreignkey')
        batch_op.drop_column('segment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('poi_segment_id_fkey'), 'segment', ['segment_id'], ['id'])

    # ### end Alembic commands ###
