"""Delete lodgingOptions

Revision ID: 07424ad5dd29
Revises: e1eae7447da4
Create Date: 2025-06-15 11:00:57.391314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07424ad5dd29'
down_revision = 'e1eae7447da4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lodging_option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lodging_option',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('variant_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('route_city.id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['day_variant.id'], name=op.f('fk_lodging_option_variant_id_day_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lodging_option'))
    )
    # ### end Alembic commands ###
