"""change check in and out on stard date and end in TripSession

Revision ID: 0958288dd7f9
Revises: 2f1c3e117760
Create Date: 2025-06-08 12:23:32.745251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0958288dd7f9'
down_revision = '2f1c3e117760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.drop_column('check_in')
        batch_op.drop_column('check_out')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
