"""make day_order not nullable to TripVote

Revision ID: 0cbc4eff97c2
Revises: 14e699f7d887
Create Date: 2025-06-09 18:56:39.749777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbc4eff97c2'
down_revision = '14e699f7d887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.alter_column('day_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.alter_column('day_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
