"""delete TransportOption and add TransportCache

Revision ID: 111d3e5c45e9
Revises: 2706ab0b6822
Create Date: 2025-06-02 03:28:54.689598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111d3e5c45e9'
down_revision = '2706ab0b6822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_city', sa.String(), nullable=False),
    sa.Column('to_city', sa.String(), nullable=False),
    sa.Column('transport_data_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transport_option')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_option',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('destination_city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_rub', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('transport_option_route_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transport_option_pkey'))
    )
    op.drop_table('transport_cache')
    # ### end Alembic commands ###
