"""add day_order to TripVote

Revision ID: 14e699f7d887
Revises: 250a26616a34
Create Date: 2025-06-09 18:56:16.851613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14e699f7d887'
down_revision = '250a26616a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.drop_column('day_order')

    # ### end Alembic commands ###
