"""add poi_description_json to Segment and delete transition property

Revision ID: 1e626637db53
Revises: e4bd254f21de
Create Date: 2025-06-02 17:56:16.961960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e626637db53'
down_revision = 'e4bd254f21de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poi_description_json', sa.Text(), nullable=True))
        batch_op.drop_column('walk_time_min')
        batch_op.drop_column('lodging_name')
        batch_op.drop_column('rating')
        batch_op.drop_column('walk_distance_m')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walk_distance_m', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lodging_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('walk_time_min', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('poi_description_json')

    # ### end Alembic commands ###
