"""detele is_expired from TripInvites

Revision ID: 1e929a8d9e73
Revises: 00e6dcbccd38
Create Date: 2025-06-18 07:02:26.071408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e929a8d9e73'
down_revision = '00e6dcbccd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_invite', schema=None) as batch_op:
        batch_op.drop_column('is_expired')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_expired', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
