"""not nullable segment type

Revision ID: 2c56eeb38b4c
Revises: 930eff5b18ff
Create Date: 2025-06-22 21:23:49.566490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c56eeb38b4c'
down_revision = '930eff5b18ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE segment SET type = 100 WHERE type is NULL")

    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.SMALLINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.SMALLINT(),
               nullable=True)

    # ### end Alembic commands ###
