"""Add location geometry for city

Revision ID: 8a0afdeb9300
Revises: 6861cc645ade
Create Date: 2025-07-02 15:41:30.377268

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '8a0afdeb9300'
down_revision = '6861cc645ade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))

    op.execute("""UPDATE city 
    SET location = ST_SetSRID(ST_MakePoint(lon, lat), 4326) 
    WHERE lat IS NOT NULL AND lon IS NOT NULL""")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('city', schema=None) as batch_op:
        batch_op.drop_index('idx_city_location', postgresql_using='gist')
        batch_op.drop_column('location')

    # ### end Alembic commands ###
