"""delete cuisine for change type

Revision ID: b9659ca4763d
Revises: 2c56eeb38b4c
Create Date: 2025-06-23 12:56:01.897955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9659ca4763d'
down_revision = '2c56eeb38b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_place', schema=None) as batch_op:
        batch_op.drop_column('cuisine')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuisine', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
