"""add CASCADE for trip session

Revision ID: 5023cc9e4418
Revises: a5f0dd23235b
Create Date: 2025-07-03 10:05:33.557889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5023cc9e4418'
down_revision = 'a5f0dd23235b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_invite', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_invite_session_uuid_trip_session'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_invite_session_uuid_trip_session'), 'trip_session', ['session_uuid'], ['uuid'], ondelete='CASCADE')

    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_participant_session_id_trip_session'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_participant_session_id_trip_session'), 'trip_session', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_vote_session_id_trip_session'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_vote_session_id_trip_session'), 'trip_session', ['session_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_vote_session_id_trip_session'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_vote_session_id_trip_session'), 'trip_session', ['session_id'], ['id'])

    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_participant_session_id_trip_session'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_participant_session_id_trip_session'), 'trip_session', ['session_id'], ['id'])

    with op.batch_alter_table('trip_invite', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_invite_session_uuid_trip_session'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_invite_session_uuid_trip_session'), 'trip_session', ['session_uuid'], ['uuid'])

    # ### end Alembic commands ###
