"""drop type meal_places and choices json

Revision ID: 72a61e502445
Revises: bcd75d5b91e9
Create Date: 2025-06-22 20:58:48.172396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72a61e502445'
down_revision = '0bd5b110c40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_place', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.drop_column('choices_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choices_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))

    with op.batch_alter_table('meal_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
