"""return type as small int for enum

Revision ID: 930eff5b18ff
Revises: 72a61e502445
Create Date: 2025-06-22 21:21:53.676356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930eff5b18ff'
down_revision = '72a61e502445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.SmallInteger(), nullable=True))

    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.SmallInteger(), nullable=True))

    with op.batch_alter_table('transport_price_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_type', sa.SmallInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_price_entry', schema=None) as batch_op:
        batch_op.drop_column('object_type')

    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('meal_place', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
