"""make not nullable dgis_id in POI

Revision ID: 20bf6019fe37
Revises: e23ee5b81981
Create Date: 2025-06-25 09:05:54.011788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20bf6019fe37'
down_revision = 'e23ee5b81981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.alter_column('dgis_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.alter_column('dgis_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
