"""delete day_variant_variant_id in DayVariant, change from day_variant_id to variant_id in TripVote

Revision ID: 250a26616a34
Revises: a8b09520eae4
Create Date: 2025-06-09 16:25:30.799777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250a26616a34'
down_revision = 'a8b09520eae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day_variant', schema=None) as batch_op:
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('trip_vote_day_variant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'day_variant', ['variant_id'], ['id'])
        batch_op.drop_column('day_variant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_variant_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('trip_vote_day_variant_id_fkey'), 'day_variant', ['day_variant_id'], ['id'])
        batch_op.drop_column('variant_id')

    with op.batch_alter_table('day_variant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('variant_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
