"""modify TransportOption

Revision ID: 2706ab0b6822
Revises: 6669ef3656d2
Create Date: 2025-06-02 03:08:49.137475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2706ab0b6822'
down_revision = '6669ef3656d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_city', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('time_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cost_rub', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.drop_column('back_cost_rub')
        batch_op.drop_column('there_time_min')
        batch_op.drop_column('there_to')
        batch_op.drop_column('there_from')
        batch_op.drop_column('there_cost_rub')
        batch_op.drop_column('back_time_min')
        batch_op.drop_column('back_to')
        batch_op.drop_column('back_from')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('back_from', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('back_to', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('back_time_min', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('there_cost_rub', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('there_from', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('there_to', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('there_time_min', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('back_cost_rub', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('cost_rub')
        batch_op.drop_column('time_min')
        batch_op.drop_column('destination_city')

    # ### end Alembic commands ###
