"""city in TripSession nullable false

Revision ID: 2f1c3e117760
Revises: ab7b0621b84e
Create Date: 2025-06-08 12:07:03.268921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1c3e117760'
down_revision = 'ab7b0621b84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.alter_column('departure_city_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.alter_column('departure_city_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
