"""add trip_session

Revision ID: 314ed117ae6d
Revises: 8f7d6c7ac7a2
Create Date: 2025-05-30 02:02:08.570078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314ed117ae6d'
down_revision = '8f7d6c7ac7a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('departure_city', sa.String(), nullable=False),
    sa.Column('departure_lat', sa.Float(), nullable=False),
    sa.Column('departure_lon', sa.Float(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_session')
    # ### end Alembic commands ###
