"""Add staff and traveler

Revision ID: 4dd2ff1769bb
Revises: bcd75d5b91e9
Create Date: 2025-06-24 16:54:50.010100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd2ff1769bb'
down_revision = 'bcd75d5b91e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_staff')),
    sa.UniqueConstraint('email', name=op.f('uq_staff_email')),
    sa.UniqueConstraint('login', name=op.f('uq_staff_login'))
    )
    op.create_table('traveler',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_traveler'))
    )
    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_participant_user_uuid_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_participant_user_uuid_traveler'), 'traveler', ['user_uuid'], ['uuid'])
    op.drop_table('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_user'))
    )
    
    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trip_participant_user_uuid_traveler'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_trip_participant_user_uuid_user'), 'user', ['user_uuid'], ['uuid'])

    op.drop_table('traveler')
    op.drop_table('staff')
    # ### end Alembic commands ###
