"""move city info to city and paste FK in routeCity

Revision ID: 547a3b76ad1b
Revises: 111d3e5c45e9
Create Date: 2025-06-02 12:39:21.655890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547a3b76ad1b'
down_revision = '111d3e5c45e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('yandex_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('yandex_code')
    )
    with op.batch_alter_table('route_city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.alter_column('route_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])
        batch_op.drop_column('name')
        batch_op.drop_column('lat')
        batch_op.drop_column('station_code')
        batch_op.drop_column('lon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_city', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('station_code', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('route_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('city_id')

    op.drop_table('city')
    # ### end Alembic commands ###
