"""check_in ckeck_out nullable

Revision ID: 6669ef3656d2
Revises: 314ed117ae6d
Create Date: 2025-05-30 10:26:48.017839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6669ef3656d2'
down_revision = '314ed117ae6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.alter_column('check_in',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('check_out',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.alter_column('check_out',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('check_in',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
