"""object_id to int PriceEntry and update_at default

Revision ID: 776b249e048c
Revises: c5345011b917
Create Date: 2025-06-10 15:18:01.962871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776b249e048c'
down_revision = 'c5345011b917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_entry', schema=None) as batch_op:
        batch_op.alter_column('object_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('transport_price_entry', schema=None) as batch_op:
        batch_op.alter_column('object_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_price_entry', schema=None) as batch_op:
        batch_op.alter_column('object_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('price_entry', schema=None) as batch_op:
        batch_op.alter_column('object_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
