"""add uuid_admin in TripSession

Revision ID: 7f36bbf21528
Revises: 8fd1d7d54b08
Create Date: 2025-06-18 10:47:42.186437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f36bbf21528'
down_revision = '8fd1d7d54b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_admin', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_trip_session_uuid_admin'), ['uuid_admin'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trip_session_uuid_admin'), type_='unique')
        batch_op.drop_column('uuid_admin')

    # ### end Alembic commands ###
