"""change base_city to entry_points_json field to Route

Revision ID: 8070de93365d
Revises: cd3399e4a14d
Create Date: 2025-05-24 18:59:03.644222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8070de93365d'
down_revision = 'cd3399e4a14d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_points_json', sa.Text(), nullable=True))
        batch_op.drop_column('base_city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_city', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('entry_points_json')

    # ### end Alembic commands ###
