"""add is_active in TripInvites

Revision ID: 8fd1d7d54b08
Revises: 1e929a8d9e73
Create Date: 2025-06-18 10:22:51.762758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd1d7d54b08'
down_revision = '1e929a8d9e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_invite', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
