"""init

Revision ID: 9209faff5611
Revises: 
Create Date: 2025-05-30 00:49:51.544880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9209faff5611'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('coords', sa.String(), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('avg_check_rub', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('last_known_price', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('estimated_budget_rub', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('there_from', sa.String(), nullable=True),
    sa.Column('there_to', sa.String(), nullable=True),
    sa.Column('there_time_min', sa.Integer(), nullable=True),
    sa.Column('there_cost_rub', sa.Integer(), nullable=True),
    sa.Column('back_from', sa.String(), nullable=True),
    sa.Column('back_to', sa.String(), nullable=True),
    sa.Column('back_time_min', sa.Integer(), nullable=True),
    sa.Column('back_cost_rub', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('day_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('est_budget', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lodging_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['day_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('poi_name', sa.String(), nullable=True),
    sa.Column('must_see', sa.Boolean(), nullable=True),
    sa.Column('arrival_window', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('meal_type', sa.String(), nullable=True),
    sa.Column('meal_options_json', sa.Text(), nullable=True),
    sa.Column('lodging_name', sa.String(), nullable=True),
    sa.Column('walk_time_min', sa.Integer(), nullable=True),
    sa.Column('walk_distance_m', sa.Integer(), nullable=True),
    sa.Column('alt_transport_json', sa.Text(), nullable=True),
    sa.Column('transition_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['day_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment')
    op.drop_table('lodging_option')
    op.drop_table('day_variant')
    op.drop_table('transport_option')
    op.drop_table('day')
    op.drop_table('route')
    op.drop_table('price_entry')
    op.drop_table('meal_place')
    # ### end Alembic commands ###
