"""add date_at TransportCache

Revision ID: 957ad4d56967
Revises: a900e6138bfa
Create Date: 2025-06-08 12:45:03.496552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '957ad4d56967'
down_revision = 'a900e6138bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_cache', schema=None) as batch_op:
        batch_op.drop_column('date_at')

    # ### end Alembic commands ###
