"""make not nullable role in staff

Revision ID: 9febf8156025
Revises: e2f2e05d1b8c
Create Date: 2025-06-25 05:15:47.672557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9febf8156025'
down_revision = 'e2f2e05d1b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.SMALLINT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.SMALLINT(),
               nullable=True)

    # ### end Alembic commands ###
