"""add link to city in TripSession

Revision ID: a64c26264319
Revises: 547a3b76ad1b
Create Date: 2025-06-02 12:52:52.647554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64c26264319'
down_revision = '547a3b76ad1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'city', ['city_id'], ['id'])
        batch_op.drop_column('departure_lat')
        batch_op.drop_column('departure_city')
        batch_op.drop_column('departure_lon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('departure_city', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('departure_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('city_id')

    # ### end Alembic commands ###
