"""init

Revision ID: a7b2d50b7b86
Revises: 
Create Date: 2025-06-14 20:50:45.903000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b2d50b7b86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('yandex_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city'))
    )
    op.create_table('poi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('must_see', sa.Boolean(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poi'))
    )
    op.create_table('price_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_entry'))
    )
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('estimated_budget_rub', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route'))
    )
    op.create_table('transport_price_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('last_known_price', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transport_price_entry'))
    )
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_order', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_day_route_id_route')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_day'))
    )
    op.create_table('meal_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('coords', sa.String(), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('avg_check_rub', sa.Integer(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_meal_place_city_id_city')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_place'))
    )
    op.create_table('route_city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], name=op.f('fk_route_city_city_id_city')),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_route_city_route_id_route')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_city'))
    )
    op.create_table('transport_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_city_id', sa.Integer(), nullable=False),
    sa.Column('end_city_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('date_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['end_city_id'], ['city.id'], name=op.f('fk_transport_cache_end_city_id_city')),
    sa.ForeignKeyConstraint(['start_city_id'], ['city.id'], name=op.f('fk_transport_cache_start_city_id_city')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transport_cache'))
    )
    op.create_table('trip_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('departure_city_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('choices_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['departure_city_id'], ['city.id'], name=op.f('fk_trip_session_departure_city_id_city')),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_trip_session_route_id_route')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_session'))
    )
    op.create_table('day_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('est_budget', sa.Integer(), nullable=True),
    sa.Column('day_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.id'], name=op.f('fk_day_variant_day_id_day')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_day_variant'))
    )
    op.create_table('simular_meal_place_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_place_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_place_id'], ['meal_place.id'], name=op.f('fk_simular_meal_place_cache_meal_place_id_meal_place')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_simular_meal_place_cache'))
    )
    op.create_table('trip_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('join_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['trip_session.id'], name=op.f('fk_trip_participant_session_id_trip_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_participant'))
    )
    op.create_table('lodging_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('route_city.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['day_variant.id'], name=op.f('fk_lodging_option_variant_id_day_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lodging_option'))
    )
    op.create_table('segment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('attached_next_segment_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('poi_id', sa.Integer(), nullable=True),
    sa.Column('lodging_name', sa.String(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attached_next_segment_id'], ['segment.id'], name=op.f('fk_segment_attached_next_segment_id_segment')),
    sa.ForeignKeyConstraint(['city_id'], ['route_city.id'], name=op.f('fk_segment_city_id_route_city')),
    sa.ForeignKeyConstraint(['poi_id'], ['poi.id'], name=op.f('fk_segment_poi_id_poi')),
    sa.ForeignKeyConstraint(['variant_id'], ['day_variant.id'], name=op.f('fk_segment_variant_id_day_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment'))
    )
    op.create_table('trip_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('day_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['trip_participant.id'], name=op.f('fk_trip_vote_participant_id_trip_participant')),
    sa.ForeignKeyConstraint(['session_id'], ['trip_session.id'], name=op.f('fk_trip_vote_session_id_trip_session')),
    sa.ForeignKeyConstraint(['variant_id'], ['day_variant.id'], name=op.f('fk_trip_vote_variant_id_day_variant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_vote'))
    )
    op.create_table('transition_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('time_min', sa.Integer(), nullable=False),
    sa.Column('cost_rub', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], name=op.f('fk_transition_option_segment_id_segment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transition_option'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transition_option')
    op.drop_table('trip_vote')
    op.drop_table('segment')
    op.drop_table('lodging_option')
    op.drop_table('trip_participant')
    op.drop_table('simular_meal_place_cache')
    op.drop_table('day_variant')
    op.drop_table('trip_session')
    op.drop_table('transport_cache')
    op.drop_table('route_city')
    op.drop_table('meal_place')
    op.drop_table('day')
    op.drop_table('transport_price_entry')
    op.drop_table('route')
    op.drop_table('price_entry')
    op.drop_table('poi')
    op.drop_table('city')
    # ### end Alembic commands ###
