"""add TripParticipant, TripVote

Revision ID: a8b09520eae4
Revises: 957ad4d56967
Create Date: 2025-06-09 09:17:25.824166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b09520eae4'
down_revision = '957ad4d56967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('join_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['trip_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trip_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_variant_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['day_variant_id'], ['day_variant.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['trip_participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_vote')
    op.drop_table('trip_participant')
    # ### end Alembic commands ###
