"""add link for city in TripSession instead departure_city

Revision ID: ab7b0621b84e
Revises: 5739dc97f8bf
Create Date: 2025-06-08 12:05:41.246241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7b0621b84e'
down_revision = '5739dc97f8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_city_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'city', ['departure_city_id'], ['id'])
        batch_op.drop_column('departure_city')
        batch_op.drop_column('departure_lon')
        batch_op.drop_column('departure_lat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('departure_lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('departure_city', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('departure_city_id')

    # ### end Alembic commands ###
