"""add is_admin attribute to Participant table

Revision ID: bcd75d5b91e9
Revises: e9f92a05b773
Create Date: 2025-06-18 13:45:58.316090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd75d5b91e9'
down_revision = 'e9f92a05b773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='False', nullable=False))
        batch_op.create_index('one_admin_for_session', ['session_id', 'is_admin'], unique=True, postgresql_where='is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.drop_index('one_admin_for_session', postgresql_where='is_admin')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
