"""add table POI

Revision ID: c5345011b917
Revises: bd40b3884ba2
Create Date: 2025-06-10 14:55:20.079136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5345011b917'
down_revision = 'bd40b3884ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('must_see', sa.Boolean(), nullable=True),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_entry_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['price_entry_id'], ['price_entry.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transport_price_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('last_known_price', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.drop_column('last_known_price')
        batch_op.drop_column('source_url')

    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attached_next_segment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('poi_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'poi', ['poi_id'], ['id'])
        batch_op.create_foreign_key(None, 'segment', ['attached_next_segment_id'], ['id'])
        batch_op.drop_column('must_see')
        batch_op.drop_column('open_hours')
        batch_op.drop_column('rating')
        batch_op.drop_column('poi_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poi_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('open_hours', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('must_see', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('poi_id')
        batch_op.drop_column('attached_next_segment_id')

    with op.batch_alter_table('price_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_known_price', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('price')

    op.drop_table('transport_price_entry')
    op.drop_table('poi')
    # ### end Alembic commands ###
