"""change entry_points_json to entry_info field to Route

Revision ID: c750a1769237
Revises: 8070de93365d
Create Date: 2025-05-24 19:05:08.672669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c750a1769237'
down_revision = '8070de93365d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_info', sa.Text(), nullable=True))
        batch_op.drop_column('entry_points_json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_points_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('entry_info')

    # ### end Alembic commands ###
