"""add date_for to TransportCache

Revision ID: cbdb0c233c2c
Revises: 6b8c01287dac
Create Date: 2025-06-03 19:22:52.808117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdb0c233c2c'
down_revision = '6b8c01287dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_for', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_cache', schema=None) as batch_op:
        batch_op.drop_column('date_for')

    # ### end Alembic commands ###
