"""Add fk to staff in request addition

Revision ID: d36057800a39
Revises: 333a99aea994
Create Date: 2025-06-27 16:53:23.403123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36057800a39'
down_revision = '333a99aea994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addition_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_addition_request_staff_id_staff'), 'staff', ['staff_id'], ['uuid'])

    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_day_route_id_route'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_day_route_id_route'), 'route', ['route_id'], ['id'])

    with op.batch_alter_table('day_variant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_day_variant_day_id_day'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_day_variant_day_id_day'), 'day', ['day_id'], ['id'])

    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_segment_variant_id_day_variant'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_segment_variant_id_day_variant'), 'day_variant', ['variant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_segment_variant_id_day_variant'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_segment_variant_id_day_variant'), 'day_variant', ['variant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('day_variant', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_day_variant_day_id_day'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_day_variant_day_id_day'), 'day', ['day_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_day_route_id_route'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_day_route_id_route'), 'route', ['route_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('addition_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_addition_request_staff_id_staff'), type_='foreignkey')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
