"""delete_price_entry_id from POI

Revision ID: df6e49e58d18
Revises: 776b249e048c
Create Date: 2025-06-10 15:30:23.248163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df6e49e58d18'
down_revision = '776b249e048c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('poi_price_entry_id_fkey'), type_='foreignkey')
        batch_op.drop_column('price_entry_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_entry_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('poi_price_entry_id_fkey'), 'price_entry', ['price_entry_id'], ['id'])

    # ### end Alembic commands ###
