"""add dgis_id to POI

Revision ID: e23ee5b81981
Revises: 9febf8156025
Create Date: 2025-06-25 09:03:54.471793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e23ee5b81981'
down_revision = '9febf8156025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dgis_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_poi_dgis_id'), ['dgis_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poi', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_poi_dgis_id'), type_='unique')
        batch_op.drop_column('dgis_id')

    # ### end Alembic commands ###
