"""Add role to staff

Revision ID: e2f2e05d1b8c
Revises: 4dd2ff1769bb
Create Date: 2025-06-25 05:14:36.772225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f2e05d1b8c'
down_revision = '4dd2ff1769bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
