"""Add departure city to TripSession

Revision ID: e4b16748e2bd
Revises: e1d9348d6cdc
Create Date: 2025-05-25 14:45:09.010261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4b16748e2bd'
down_revision = 'e1d9348d6cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_city', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('departure_lat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('departure_lon', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.drop_column('departure_lon')
        batch_op.drop_column('departure_lat')
        batch_op.drop_column('departure_city')

    # ### end Alembic commands ###
