"""add price to Lodging and modify to nullable some property

Revision ID: e4bd254f21de
Revises: a64c26264319
Create Date: 2025-06-02 17:39:17.165905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4bd254f21de'
down_revision = 'a64c26264319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lodging_option', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_check_rub', sa.Integer(), nullable=True))

    with op.batch_alter_table('route_city', schema=None) as batch_op:
        batch_op.alter_column('route_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_city', schema=None) as batch_op:
        batch_op.alter_column('city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('route_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('lodging_option', schema=None) as batch_op:
        batch_op.drop_column('avg_check_rub')

    # ### end Alembic commands ###
