"""add User

Revision ID: e9f92a05b773
Revises: 7e3a9b49b434
Create Date: 2025-06-18 13:08:43.414815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f92a05b773'
down_revision = '7e3a9b49b434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_user'))
    )
    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_uuid', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_trip_participant_uuid'), type_='unique')
        batch_op.create_foreign_key(batch_op.f('fk_trip_participant_user_uuid_user'), 'user', ['user_uuid'], ['uuid'])
        batch_op.drop_column('uuid')
        batch_op.drop_column('name')

    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_trip_session_uuid_admin'), type_='unique')
        batch_op.drop_column('uuid_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid_admin', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_trip_session_uuid_admin'), ['uuid_admin'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('trip_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_trip_participant_user_uuid_user'), type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('uq_trip_participant_uuid'), ['uuid'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('user_uuid')

    op.drop_table('user')
    # ### end Alembic commands ###
