"""change day_number to day_order Day

Revision ID: ea2cc63f1962
Revises: 0cbc4eff97c2
Create Date: 2025-06-09 22:51:34.824129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2cc63f1962'
down_revision = '0cbc4eff97c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_order', sa.Integer(), nullable=True))
        batch_op.drop_column('day_number')

    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'trip_session', ['session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('session_id')

    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('day_order')

    # ### end Alembic commands ###
