"""change entry_info to entry_info_json field to Route

Revision ID: f5982d852693
Revises: c750a1769237
Create Date: 2025-05-24 19:23:53.776212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5982d852693'
down_revision = 'c750a1769237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_info_json', sa.Text(), nullable=True))
        batch_op.drop_column('entry_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_info', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('entry_info_json')

    # ### end Alembic commands ###
